name: Clean up test reports

on:
  delete:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'branch'

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove report directory for deleted branch
        run: |
          BRANCH_NAME="${{ github.event.ref }}"
          if [ -d "$BRANCH_NAME" ]; then
            echo "Removing report directory for branch: $BRANCH_NAME"
            rm -rf "$BRANCH_NAME"

            # Check if there are actually changes to commit
            if [ -n "$(git status --porcelain)" ]; then
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"

              # Try to push changes up to 5 times with exponential backoff
              for i in {1..5}; do
                echo "Attempt $i to push changes..."

                # Stage our changes first
                git add .

                # Check if we actually have changes to commit
                if git diff --staged --quiet; then
                  echo "No staged changes to commit"
                  exit 0
                fi

                # Commit our changes
                git commit -m "Remove test reports for deleted branch: $BRANCH_NAME"

                # Try to push
                if git push; then
                  echo "Successfully pushed changes on attempt $i"
                  exit 0
                else
                  echo "Push failed on attempt $i, trying to rebase..."

                  # Reset to before our commit
                  git reset --soft HEAD~1

                  # Pull with rebase
                  if git pull --rebase origin gh-pages; then
                    echo "Rebase successful, will retry commit and push"
                  else
                    echo "Rebase failed on attempt $i, retrying from scratch..."
                    # Reset any staged changes and start over
                    git reset --hard HEAD
                    sleep $((i * 2))
                    continue
                  fi
                fi

                # Exponential backoff: wait 2, 4, 8, 16 seconds
                sleep $((i * 2))
              done

              echo "Failed to push after 5 attempts"
              exit 1
            else
              echo "No changes detected after removing directory"
            fi
          else
            echo "Directory $BRANCH_NAME does not exist, nothing to clean up"
          fi
