name: Dispatch E2E Tests

on:
  push:

jobs:
  e2eaabb:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: "🧪 Trigger E2E Tests"
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: grasword/monty-hall-problem
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: aabb
