name: Dispatch E2E Tests

on:
  push:

jobs:
  e2eaabb:
    runs-on: ubuntu-latest

    steps:
      - name: 11111
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: grasword/monty-hall-problem
          token: fffff
          event-type: aabb
