name: Dispatch E2E Tests

on:
  push:

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: "🧪 Trigger E2E Tests"
        uses: peter-evans/repository-dispatch@v3
        with:
          # repository: ${{ github.repository }}
          # token: ${{ secrets.GITHUB_TOKEN }}
          event-type: platform-environment-ready
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
