name: Test Dispatch
on: push

permissions:
  pull-requests: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test repository dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          # token: ${{ secrets.PUBLIC_REPO_SCOPED_TOKEN }}
          # comment out the token to use the default token
          event-type: tests
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
